/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AboutDialog.java
 *
 * Created on Aug 11, 2011, 5:40:03 PM
 */
package wGUI;

import plugin.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author omarwagih
 */
public class AboutDialog extends javax.swing.JDialog {
    private final String VERSION = "v1.0";
    private String pluginInfo;
    JFrame mainFrame;
    
    /** Creates new form AboutDialog */
    public AboutDialog(java.awt.Frame parent, boolean modal, JFrame mainFrame) {
        super(parent, modal);
        
        this.mainFrame = mainFrame;
        String cite = "Wagih, O., Hao, Y., Pu, S., Merkoulovitch, A., Vlasblom, J., Turner, B., Wodak, S.J. "
                + "GIPro: integrated visualization of genetic and physical interactions in the context of protein complexes. "
                +"<i>Unpublished</i>";
        
        pluginInfo = 
        "<html>This tool uses physical and genetic interaction data to identify the functional relationships " +
        "between genes. There are two parts to the analysis, and parameters should be provided for each.<br>" +
        "In the first part, relations values are filtered based on calculated or provided cutoff values. " +
        "The enrichment analysis is then run on the data, using either the Fisher Exact Test or simulations. " +
        "You can roll over any of the fields for more information<br><br>"
                
        + "<b>Please cite as:</b><br>"
        + cite
        + "</html>";
        
        initComponents();
        bodyEditorPane.setText(pluginInfo);
        bodyEditorPane.setEditable(false);
        bodyEditorPane.setCaretPosition(0);
        versionLabel.setText(VERSION);
        
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int X = (screen.width / 2) - (getWidth() / 2); // Center horizontally.
        int Y = (screen.height / 2) - (getHeight() / 2); // Center vertically.

        setBounds(X,Y , getWidth(),getHeight());
        
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        versionLabel = new javax.swing.JLabel();
        GIPro_logo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bodyEditorPane = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setUndecorated(true);

        versionLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 3, 18));
        versionLabel.setText("v1.0");

        GIPro_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gipro_logo.png"))); // NOI18N

        jLabel2.setText("Genetic Interactions Pro plugin for Cytoscape");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel2)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(GIPro_logo)
                        .add(2, 2, 2)
                        .add(versionLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(GIPro_logo)
                    .add(versionLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bodyEditorPane.setContentType("text/html");
        bodyEditorPane.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        bodyEditorPane.setOpaque(false);
        jScrollPane1.setViewportView(bodyEditorPane);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(140, 140, 140)
                .add(jButton1)
                .addContainerGap(151, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 118, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    //restore window
    mainFrame.setAlwaysOnTop(true);
    mainFrame.setAlwaysOnTop(false);
    this.dispose();
    
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                AboutDialog dialog = new AboutDialog(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GIPro_logo;
    private javax.swing.JEditorPane bodyEditorPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration//GEN-END:variables
}
